SELECT
    CITY,
    SUM(
        CASE WHEN LOWER(ROOM_TYPE) LIKE '%/apt' THEN 1 ELSE 0 END
    ) AS APT_COUNT,
    SUM(
        CASE WHEN LOWER(ROOM_TYPE) LIKE 'private %' THEN 1 ELSE 0 END
    ) AS PRIVATE_COUNT,
    SUM(
        CASE WHEN LOWER(ROOM_TYPE) LIKE 'shared %' THEN 1 ELSE 0 END
    ) AS SHARED_COUNT
FROM
    airbnb_search_details
GROUP BY
    CITY
ORDER BY
    APT_COUNT DESC,
    PRIVATE_COUNT DESC,
    SHARED_COUNT DESC