WITH CTE AS (
    SELECT COUNTRY, WINERY, 
           AVG(POINTS) AS TOTAL_AVERAGE, 
           DENSE_RANK() OVER (PARTITION BY COUNTRY ORDER BY AVG(POINTS) DESC, WINERY ASC) AS WINERY_RANK
    FROM 
        WINEMAG_P1
    GROUP BY 
        COUNTRY, WINERY
    ORDER BY 
        COUNTRY, TOTAL_AVERAGE DESC
)
SELECT * 
FROM 
    CTE;
