WITH CTE AS(
    SELECT
        U.NAME,
        U.ID,
        SUM(COALESCE(R.DISTANCE, 0)) AS TRAVELLED_DISTANCE
    FROM
        USERS AS U
        LEFT JOIN RIDES AS R ON U.ID = R.USER_ID
    GROUP BY
        U.NAME,
        U.ID
)
SELECT
    NAME,
    TRAVELLED_DISTANCE
FROM
    CTE
ORDER BY
    TRAVELLED_DISTANCE DESC,
    NAME ASC