SELECT
    D.DEPT_NAME AS DEPT_NAME,
    COUNT(S.STUDENT_ID) AS STUDENT_NUMBER
FROM
    DEPARTMENT AS D
    LEFT JOIN STUDENT AS S ON D.DEPT_ID = S.DEPT_ID
GROUP BY
    DEPT_NAME
ORDER BY
    STUDENT_NUMBER DESC,
    DEPT_NAME ASC