WITH CTE AS(
    SELECT
        COMPANY_ID,
        TITLE,
        DESCRIPTION,
        COUNT(*) AS TOTAL_DUPLICATE_JOBS
    FROM
        JOB_LISTINGS
    GROUP BY
        1,
        2,
        3
)
SELECT
    COUNT(TOTAL_DUPLICATE_JOBS) AS DUPLICATE_COMPANIES
FROM
    CTE
WHERE
    TOTAL_DUPLICATE_JOBS > 1;