WITH CTE AS(
    SELECT
        P.PAGE_ID,
        PL.LIKED_DATE
    FROM
        PAGES AS P
        LEFT JOIN PAGE_LIKES AS PL ON P.PAGE_ID = PL.PAGE_ID
)
SELECT
    PAGE_ID
FROM
    CTE
WHERE
    LIKED_DATE IS NULL
ORDER BY
    PAGE_ID